# Generated by Django 4.1.3 on 2023-01-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='short_desc',
            field=models.CharField(blank=True, default='', max_length=10000, null=True, verbose_name='desc'),
        ),
        migrations.AlterField(
            model_name='places',
            name='decription',
            field=models.CharField(db_index=True, max_length=5000, verbose_name='decription'),
        ),
    ]
